name: Publish package to GitHub Packages
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Run Publish
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: clean assemble publish
        env:
          GITHUB_ACTOR: ${{ secrets.GRADLE_GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GRADLE_GITHUB_TOKEN }}